### ISSUE TITLE
Порядок подключения стилей/скриптов

### ISSUE THREAD

**Issue by yuchiko** [boxior/site-jwood#3]
Ты забыл, что порядок подключение имеет свою важность

```
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/media.css">
    <link rel="stylesheet" href="css/fonts.css">
```

почему шрифты последними идут, зачем они вообще вынесены отдельно ? Зачем вообще всё вынесено отдельно? почему файл не один?

**Comment by boxior** [comment]
Все перенес в один файл syle.css, сначала шрифты запустил, потом основной стиль и потом Медиа запросы
