### ISSUE TITLE
Не согласен, что это section

### ISSUE THREAD

**Issue by yuchiko** [boxior/site-jwood#5]
Возможно стоит еще раз прочитать когда использовать этот тег

```
        <section>
          <div>
            <img src="img/LogoTM.png" alt="">
            <h1 class="h1"><b>JWOOD</b>PHOTOGRAPHY</h1>
          </div>
        </section>
```

**Comment by boxior** [comment]
заменил сдесь тег Section на Figure(Иногда бывает необходимо разместить изображение и прилагающийся к нему текст как единую иллюстрацию. Элемент figure указывает на то, что текст и изображение являются частями единого целого.)
